#!/bin/bash
#PBS -A ebf11_c_g_vc_default
#PBS -q hprc
#PBS -l nodes=1:ppn=1
#PBS -l feature=rhel7
#PBS -l walltime=12:00:00
#PBS -l pmem=2gb
#PBS -j oe
#PBS -N sdo_data

echo "Starting job $PBS_JOBNAME"
date
echo "Job id: $PBS_JOBID"
echo "About to change into $PBS_O_WORKDIR"
cd $PBS_O_WORKDIR
echo "About to start Julia"
python /storage/home/mlp95/work/sdo-pypline/script/download_data.py /storage/home/mlp95/scratch/sdo_data 2014/01/01 24
echo "Julia exited"
date
