#!/bin/bash
#PBS -A dfc13_mri
#PBS -l qos=mgc_open
#PBS -l nodes=1:ppn=1
#PBS -l feature=rhel7
#PBS -l walltime=24:00:00
#PBS -l pmem=4gb
#PBS -j oe
#PBS -N sdo_jul

echo "Starting job $PBS_JOBNAME"
date
echo "Job id: $PBS_JOBID"
echo "About to change into $PBS_O_WORKDIR"
cd $PBS_O_WORKDIR
echo "About to start Python"
source /storage/home/mlp95/work/sw/anaconda3/bin/activate
conda activate solar
python /storage/home/mlp95/work/sdo-pypline/scripts/run_pipe.py jul
date
